#!/bin/bash

function show_usage()
{
    printf "Usage: $0 <command>\n"
    cat <<EOF
    -u|--docker-compose-up
    -d|--docker-compose-down
    -c|--clean-all
    -i|--run-test-scripts-in-spark
    -g|--run-setup-postgresql
    -s|--status
    -p|--pyspark-shell
    -P|--login-to-postgresql
    -S|--login-to-spark
    -h|--help
EOF
  exit 1
}

if [[ $# -lt 1 ]]; then
    show_usage $@
fi

function docker_login_postgresql()
{
    docker-compose exec postgresdb bash
}

function docker_login_spark()
{
    docker-compose exec spark-master bash
}

function docker_up()
{
    docker-compose up --detach
}

function docker_down()
{
    docker-compose down
}

function docker_clean_all()
{
    docker-compose rm -s -f
}

function docker_status()
{
    docker-compose ps -a
    docker-compose logs postgresdb | tail -10
}

function docker_run_pyspark()
{
    docker-compose exec -w /spark spark-master ./bin/pyspark --conf spark.sql.catalogImplementation=hive
}

function run_test_scripts_in_spark()
{
    docker-compose exec -w /scripts spark-master ./run-test-scripts
}

function setup_postgresql()
{
    ./postgresql/scripts/run-setup-from-outside-container.sh
}

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -S|--login-spark)
        shift
        docker_login_spark
        ;;
    -P|--login-postgresql)
        shift
        docker_login_postgresql
        ;;
    -u|--docker-compose-up)
        shift
        docker_up
        ;;
    -d|--docker-compose-down)
        shift
        docker_down
        ;;
    -c|--clean-all)
        shift
        docker_clean_all
        ;;
    -s|--status)
        shift
        docker_status
        ;;
    -p|--pyspark-shell)
        shift
        docker_run_pyspark
        ;;
    -i|--run-test-scripts)
        shift
        run_test_scripts_in_spark
        ;;
    -g|--run-setup-postgresql)
        shift
        setup_postgresql
        ;;
    -h|--help)
        show_usage
      ;;
    *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done
