# docker-compose.yml
version: '3'
services:
  postgresdb:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ".:/shared:rw"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database-data: # named volumes can be managed easier using docker-compose
